In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
arr8 = np.arange(-28, 28, 4)
print(arr8)


[-28 -24 -20 -16 -12  -8  -4   0   4   8  12  16  20  24]


In [ ]:
marks = np.array([[20, 30, 40, 50, 60],
                  [10, 20, 30, 40, 50],
                  [50, 60, 70, 80, 90],
                  [30, 40, 50, 60, 70],
                  [60, 70, 80, 90, 100]])
print(marks[3, 1])
print(marks[1:3,1:3])
print(marks[2,:])
new_marks = marks.transpose()
print(new_marks)

40
[[20 30]
 [60 70]]
[50 60 70 80 90]
[[ 20  10  50  30  60]
 [ 30  20  60  40  70]
 [ 40  30  70  50  80]
 [ 50  40  80  60  90]
 [ 60  50  90  70 100]]


In [ ]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 @ a2)
print(a1%a2)
print(a1**a2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[1 2]
 [3 4]]
[[    1    64]
 [ 2187 65536]]


In [ ]:
arr7 = np.arange(-28, 28 , 4)
print(arr7)
print(arr7[2:7])
print(arr7[::-1])

[-28 -24 -20 -16 -12  -8  -4   0   4   8  12  16  20  24]
[-20 -16 -12  -8  -4]
[ 24  20  16  12   8   4   0  -4  -8 -12 -16 -20 -24 -28]


In [ ]:
sorted_arr = np.sort(marks)
print(sorted_arr)
print(np.sort(marks, axis=0))

[[ 20  30  40  50  60]
 [ 10  20  30  40  50]
 [ 50  60  70  80  90]
 [ 30  40  50  60  70]
 [ 60  70  80  90 100]]
[[ 10  20  30  40  50]
 [ 20  30  40  50  60]
 [ 30  40  50  60  70]
 [ 50  60  70  80  90]
 [ 60  70  80  90 100]]


In [ ]:
print(np.concatenate((a1, a2)))
print(np.concatenate((a1, a2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
